### ISSUE TITLE
Fix installation and dependency management

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#1]
We included python package dependencies in an environment created with virtualenv, and checked it into source control. Virtualenv is apparently not meant to be used in this way, as running source env/bin/activate fails on machines other the one where it was created, since it includes hard-coded paths to the original user's home directory.

### To do 
- delete the env/ folder. 
- remove "source ../env/bin/activate" from scripts in bin/.
- use pip requirements.txt or another method to specify dependencies, and document setup instructions on the wiki.
- configure such that "pip install https://github.com/StanfordBioinformatics/xppf" completes installation.

You can see and example of "pip install {repo URL}" here: http://django-mongodb-engine.readthedocs.org/en/latest/tutorial.html

**Comment by nhammond** [comment]
Added requirements.txt, deleted env/ folder and references to it.
Todo: make it possible to "pip install {git repo}"

**Comment by isaacliao** [comment]
Implemented in 463e58d79a03f4e08696a1e247d490d8b549af82
- "pip install loomengine" works
