### ISSUE TITLE
Provide user feedback about which steps are currently running, and why steps aren't running

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#10]
Currently dashboard only shows whether steps are complete or not. Would make troubleshooting / debugging much easier.

**Comment by nhammond** [comment]
Requirements:
1. When Loom attempts to run a task, report back these stages: Provisioning worker, starting worker process, running, done.
2. If any step fails, report back a status that reflects the point of failure: failed to provision worker, failed to start worker process, worker process timed out, worker process stopped responding, worker process finished with errors.
3. The worker will have a heartbeat function. The server will detect when communication is lost and can change the state of the task to failed.
4. When a task fails, update the status of the step, workflow(s), and runrequest that contain it. Depending on settings, kill other tasks or continue to run as far as possible.
5. Cleanup of VMs for finished, failed and canceled tasks. Create a setting to preserve VMs for debugging.

**Comment by nhammond** [comment]
Detailed status info implemented by #209 . Failure recovery and preserving run directories for failed steps will be handled separately.
