### ISSUE TITLE
Cache server info and allow switching between servers in different GCP projects

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#101]
Currently we have designed the client for only two server locations: local or gcloud. To resolve and access a server in GCP, we need the following info:
- project ID
- instance name
- service account email
- pkey.pem

It would be impractical to ask a user to provide this info every time when switching between servers. We should save service account email and pkey.pem for each project, and let users switch between servers by providing project ID and server instance name.

**Comment by isaacliao** [comment]
Instead of caching server info, it might be possible to just cache project info and credentials, and use Ansible dynamic inventory and GCE tags to query for possible Loom servers. Could then list possible servers for the user and let them pick one.

Would have the advantage of not getting out of sync (for instance, if an instance were deleted through the GCP dev console).

Would have to store multiple gce.ini's and multiple pkey.pem's, and have Ansible query them all. Possible by giving a directory to GCE dynamic inventory: http://docs.ansible.com/ansible/guide_gce.html

**Comment by nhammond** [comment]
Considered a rare use case, but in 0.3.0 this can be done as follows:

```
# First server
loom server start --settings-file local.conf
# Second server with different settings home, 
# name (so that docker container names do not collide) and port
LOOM_SETTINGS_HOME=~/.loom2 loom server start --settings-file local.conf -e LOOM_SERVER_NAME=loom-local2 -e LOOM_HTTP_PORT=81 
```
