### ISSUE TITLE
Timestamps in filenames should be local time

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#104]
When the setting KEEP_DUPLICATE_FILES == True, files imported to Loom have a time stamp included in their file name. Currently that is UTC, but it will be clearer to users if it uses their local timezone. (timestamps in the database should remain UTC, but this is distinct).

**Comment by somalee** [comment]
Where/when do we get timestamp? What is the timestamp being used for - if it is just name, it doesn't matter but if actions are taken based on the timestamp, it might? My understanding is that this is a big problem to stay synchronized with potentially sophisticated solutions but I am not aware of the specifics here. On-prem, there can definitely be problem with server timestamp - seen this loads of times.

**Comment by nhammond** [comment]
There are 2 places that we use timestamps. 1) Most of the objects in the database have a timestamp for time created and last update, and these are always recorded in UTC/GMT. They don't play any role in processing results, just for record keeping.

2) What this issue applies to is the name of the files on disk in storage after import. We name the file by {timestamp}-{file_id}-{filename}. Something like this:

20160610182152-7912fc8fb18843f1bdf15612025dc790-hello.txt

The main purpose of the timestamp is so that "ls" will display files sorted by creation time to make files easier to browse. For example, in the directory where uploaded files are written, you'll see them listed in the order of upload. The filename also has a unique ID that matches the corresponding database object and ends with the filename that the user assigned. As far as Loom is concerned, that timestamp doesn't mean anything--it's just a user convenience, and it can be any name that's unique in the directory.

**Comment by nhammond** [comment]
This creates more problems than it solves. Timestamps remain in UTC until they are rendered by the browser or commandline client. Closing without action.
