### ISSUE TITLE
Sporadic failure with apt-get on creating loom server

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#109]
(env) DN0a22f16f:Downloads nhammond$ loom server start

PLAY [Start the Loom server.] **************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

(env) DN0a22f16f:Downloads nhammond$ loom server create
Created deploy settings at /Users/nhammond/.loom/gcloud_deploy_settings.ini.

PLAY [Create a new instance for the Loom server.] ******************************

TASK [Create a boot disk with the same name as the server instance.] ***********
changed: [localhost]

TASK [Boot up a new instance.] *************************************************
changed: [localhost]

TASK [Wait for SSH to come up.] ************************************************
ok: [localhost] => (item={u'status': u'RUNNING', u'network': u'default', u'zone': u'us-central1-a', u'tags': [], u'image': u'container-vm-v20160321-2', u'disks': [u'loom-master'], u'name': u'loom-master', u'public_ip': u'130.211.174.56', u'private_ip': u'10.240.0.5', u'machine_type': u'n1-standard-1', u'metadata': {}})

TASK [Add host to groupname.] **************************************************
changed: [localhost] => (item={u'status': u'RUNNING', u'network': u'default', u'zone': u'us-central1-a', u'tags': [], u'image': u'container-vm-v20160321-2', u'disks': [u'loom-master'], u'name': u'loom-master', u'public_ip': u'130.211.174.56', u'private_ip': u'10.240.0.5', u'machine_type': u'n1-standard-1', u'metadata': {}})

PLAY [Set up the Loom server on the new instance.] *****************************

TASK [setup] *******************************************************************
ok: [130.211.174.56]

TASK [Update apt-get cache.] ***************************************************
fatal: [130.211.174.56]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to lock apt for exclusive operation"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Users/nhammond/work/loom2/loom/loom/client/gcloud_create_playbook.retry

PLAY RECAP *********************************************************************
130.211.174.56             : ok=1    changed=0    unreachable=0    failed=1   
localhost                  : ok=4    changed=3    unreachable=0    failed=0

**Comment by isaacliao** [comment]
Can't reproduce this on be0e713.

**Comment by nhammond** [comment]
Ok, it's only been seen once. Leaving this closed as not reproducible unless it comes up again.

**Comment by nhammond** [comment]
Issue reopened.

Other sporadic errors are arising, so far only from Nate's laptop.

Timed out attempting ssh once. On the next attempt, errored because ssh keys already existed.

**Comment by isaacliao** [comment]
I got "Failed to lock apt for exclusive operation" today. Looked into it, and this appears to happen when you either don't have sufficient permissions, or apt/dpkg is already in use. We're running as root, and re-running the playbook works, so in our case it appears to be the latter. I added retries to the apt tasks in the playbook (d55d2ed), and that seems to solve the problem.

**Comment by nhammond** [comment]
Similar sporadic failures below. These happened within a few minutes of each other, on separate VMs. This is when executing "loom server create". A few minutes later the command succeeded, with no changes.

TASK [loom_master : Install pip, which is needed to install docker-py.] ********
fatal: [104.155.169.47]: FAILED! => {"changed": false, "failed": true, "msg": "Failure talking to yum: failure: repodata/3f8640a8c7d30406008101a0754c8b89ac478cdeff21f35113c41a702781604f-primary.sqlite.xz from epel: [Errno 256] No more mirrors to try.\nhttp://download.fedoraproject.org/pub/epel/7/x86_64/repodata/3f8640a8c7d30406008101a0754c8b89ac478cdeff21f35113c41a702781604f-primary.sqlite.xz: [Errno 14] HTTP Error 404 - Not Found"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Users/s0198839/work/loom2/loom/loom/playbooks/gcloud_create_server.retry

PLAY RECAP *********************************************************************
104.155.169.47             : ok=14   changed=13   unreachable=0    failed=1   
localhost                  : ok=4    changed=3    unreachable=0    failed=0 




-----




fatal: [104.154.100.39]: FAILED! => {"changed": false, "failed": true, "msg": "Failure talking to yum: updates: Check uncompressed DB failed"}

**Comment by isaacliao** [comment]
I should add some retries to the playbook in case this is just a sporadic connection issue.

**Comment by nhammond** [comment]
Seems to be resolved by retries. No longer seeing sporadic failures on software installs.
