### ISSUE TITLE
Passing user settings file when running "loom server start" not supported

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#119]
Currently we require user settings files to be passed using "loom server create". This is by design, to prevent the misconception that settings can be updated on servers just by stopping and starting the server. In particular, settings that affect VM creation, such as instance type, require deleting and re-creating the instance.

However, users will probably use "loom server start" to implicitly create servers that don't exist yet. We should accept user settings files in this case, because otherwise implicit server creation can only happen with default settings.

To prevent confusion, the client should check for an existing server when the user runs "loom server start --settings". If no server exists, pass the settings file to "loom server create --settings." If there is already a server, provide an error message explaining that passing settings files only works on server instance creation.

**Comment by nhammond** [comment]
Are we requiring the "loom server create" step now? If so that simplifies the design here.

**Comment by isaacliao** [comment]
Yes, creating a server with non-default settings currently requires "loom server create." We can make this the required workflow.

**Comment by nhammond** [comment]
Ok, I think it makes sense to force the create step, at least when custom settings are required. I don't think it would cause too much confusion to implicitly create with default settings if the user runs "loom server start" without create, but I do think it would be cluttered to accept a "settings" argument on both create and start.

**Comment by isaacliao** [comment]
Per scrum discussion, we've decided to remove the --settings option from "loom server start". This means that custom settings must be passed using "loom server create --settings". In addition, running "loom server start" with no server.ini should set, create, and start a local server with default settings.

**Comment by isaacliao** [comment]
Also, running "loom server start" with a server.ini pointing to gcloud, but without first running "loom server create", should create and start a gcloud server using default settings, project ID from gcloud CLI, and default Compute Engine service account.

**Comment by isaacliao** [comment]
Obsolete, "loom server create" and "loom server start" have been merged into a single command.
