### ISSUE TITLE
Restarting Loom server Docker container fails if gcloud ssh keys already exist

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#127]
This is because ssh-keygen prompts for confirmation before overwriting SSH keys. `echo -e  'y\n' | ssh-keygen -q...` apparently doesn't work.

**Comment by nhammond** [comment]
Resolved with #216 
Uses the ansible user module instead of ssh-keygen. This reaches the desired state whether or not the key existed before.
