### ISSUE TITLE
Error Message while parsing Workflow Definition file is not intuitive

### ISSUE THREAD

**Issue by sowmiu** [StanfordBioinformatics/loom#130]
If any of the fixed input files have either a wrong FILE ID or has not been imported to LOOM then the import workflow step throws the following message. We should inform the user which file name and ID is causing the error

Error Message >>
1.         assert len(file_data_objects) == 1, 'expected one file but found %s: %s' % (len(file_data_objects), file_data_objects)

Exception Type: AssertionError at /api/abstract-workflows/
Exception Value: expected one file but found 0: []
Request information:
GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

**Comment by nhammond** [comment]
Fixed in b1ea06385bb67cb7d64ae031813583ae3bd9c20b

Error is now this:

ERROR! {u'non_field_errors': [u'No file found that matches value "nofile.txt"']}
