### ISSUE TITLE
Empty Run requests with just start time is entered into db when run request fails

### ISSUE THREAD

**Issue by sowmiu** [StanfordBioinformatics/loom#131]
If submitting a run request fails due to invalid input channel name or file id, an empty run request is being entered in db with empty run id and run status

**Comment by nhammond** [comment]
We should consider wrapping all requests in transactions but evaluate performance. If performance is too great, we have to be more rigorous in validation up-front, or handle things case by case whenever creating a nested object will raise an exception.

**Comment by nhammond** [comment]
RunRequest object has been eliminated with PR #414 , so this is obsolete.
