### ISSUE TITLE
'loom server delete' should clean up SSH keys on google cloud

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#133]
Ansible communicates with remote instances using SSH. Therefore, the Loom client needs to register a private SSH key with the project to create a server, and the Loom server needs to do the same to create workers.

Ideas:
- Instead of creating new SSH keys, we could store each user's private SSH key somewhere in the project (such as a storage bucket) and copy it to Loom clients and servers. 
- If every server has a unique private SSH key, we could remove its public counterpart from the project metadata when running "loom server delete".

**Comment by nhammond** [comment]
No longer causing errors due to a fix at Google that uses some logic to delete stale keys when metadata exceeds 32kb. 

Leaving this open as a lower-priority ticket to properly clean up ssh keys, but with no risk of hitting an error. Renaming accordingly.

**Comment by isaacliao** [comment]
With the shift to instance metadata, SSH keys should now be automatically deleted with the instance.
