### ISSUE TITLE
Silent failure to accept custom settings when local_deploy_settings.ini already exists

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#140]
loom server set local
loom server create --settings ~/settings.ini
loom server start

where settings.ini contains:

[local]
LOOM_MYSQL_HOST = {omitted}
LOOM_MYSQL_USER = root
LOOM_MYSQL_DB_NAME = loom
LOOM_MYSQL_PASSWORD = {omitted}

This uses SQLite for the database, which suggests that Loom is not getting these variables from the settings file. But setting them in the environment works, and Loom connects to the MYSQL host.

**Comment by isaacliao** [comment]
Hmm, do you already have ~/.loom/local_deploy_settings.ini? This is created by "loom server create", but doesn't get overwritten if it already exists. We should probably change this behavior since we're supporting user settings in a different way now.

**Comment by nhammond** [comment]
That's right. After I remove local_deploy_settings.ini, settings are properly passed.

So the problem is silent failure to accept custom settings when local_deploy_settings.ini already exists.

**Comment by isaacliao** [comment]
Fixed in 7678239c959c3b627fcf4c40fefc7f6c5d7152b3. "loom server create" now overwrites pre-exiting local_deploy_settings.ini and gcloud_deploy_settings.ini.
