### ISSUE TITLE
SSL Cert Name too long

### ISSUE THREAD

**Issue by cmuthu** [StanfordBioinformatics/loom#160]
Part of the installation log:

PLAY RECAP *********************************************************************
10.128.0.10                : ok=12   changed=11   unreachable=0    failed=1   
localhost                  : ok=4    changed=3    unreachable=0    failed=0   

Creating or updating ~/.loom/gce.ini...
Creating ~/.loom/gce_key.json...
Created deploy settings at /home/s0194353/.loom/gcloud_deploy_settings.ini.
Configuring SSH keys for gcloud...
+ loom server start

PLAY [Start the Loom server.] **************************************************

TASK [setup] *******************************************************************
ok: [test-loom-server-2016aug23-165829]

TASK [Start the Loom server.] **************************************************
fatal: [test-loom-server-2016aug23-165829]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/s0194353/loom/loom/playbooks/gcloud_start_server.retry

PLAY RECAP *********************************************************************
test-loom-server-2016aug23-165829 : ok=1    changed=0    unreachable=0    failed=1

**Comment by nhammond** [comment]
Can you share the script you are using for startup, at least everything from "loom server set" to "loom server start"? Also, can you share the custom settings file that you used?

**Comment by cmuthu** [comment]
it is checked in at: cgsdev/cgstafat/tools/loom_server

**Comment by cmuthu** [comment]
I can leave the client vm :s0194353@test-loom-client-2016aug23-165829

the log is in log.out at ~s0194353.

**Comment by cmuthu** [comment]
TASK [loom_master : Create self-signed SSL certificate and key.] ***************
fatal: [10.128.0.10]: FAILED! => {"changed": true, "cmd": ["openssl", "req", "-x509", "-nodes", "-days", "365", "-newkey", "rsa:2048", "-keyout", "/root/.loom/ssl/ssl.key", "-out", "/root/.loom/ssl/ssl.crt", "-subj", "/C=US/ST=California/L=Palo Alto/O=Stanford University/CN=test-loom-server-2016aug23-165829.c.gbsc-gcp-project-scgs-dev.internal"], "delta": "0:00:00.112610", "end": "2016-08-24 00:04:23.105219", "failed": true, "rc": 1, "start": "2016-08-24 00:04:22.992609", "stderr": "Generating a 2048 bit RSA private key\n............................................+++\n...................+++\nwriting new private key to '/root/.loom/ssl/ssl.key'\n-----\nproblems making Certificate Request\n140132627503008:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=64", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by isaacliao** [comment]
The max length of the CN (Common Name) field is 64 characters: http://security.stackexchange.com/questions/40026/openssl-x509-whats-the-significance-of-cn-common-name

"test-loom-server-2016aug23-165829.c.gbsc-gcp-project-scgs-dev.internal" is 70 characters.

I can fix this by using the node name instead of the fully qualified name, since Google Cloud instance names are limited to 63 characters.

**Comment by isaacliao** [comment]
Fixed in f5d76583b51d0315de4ca3a17b412040ce1d08a4
