### ISSUE TITLE
Silent failure when running a workflow by copying and pasting workflow ID

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#187]
Reported by Sowmi. Trying to run a workflow by copying and pasting the workflow ID fails silently.
The server returns a run request ID, but doesn’t actually run it. However, manually typing in the workflow ID works.

**Comment by nhammond** [comment]
Not clear. Is this using the "loom run" command in both cases?

**Comment by isaacliao** [comment]
CC'ing Sowmi for more details.

________________________________

**Comment by nhammond** [comment]
Closing as unable to reproduce.
