### ISSUE TITLE
During creation, Loom server VM sometimes unreachable via SSH from client VM after "wait for SSH" step

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#188]
Reported by Ranjan. During "loom server create", the "Wait for SSH to come up" step completes successfully, but then fails later with "Failed to connect to the host via ssh." Manually SSHing to the client VM, then SSHing to the server VM, works with no issues.
```
Generating public/private rsa key pair.
Your identification has been saved in /home/s0194353/.ssh/google_compute_engine.
Your public key has been saved in /home/s0194353/.ssh/google_compute_engine.pub.
The key fingerprint is:
0e:53:75:02:9c:ea:7d:23:dd:b5:6e:69:e9:d8:fb:d1 s0194353@t-lm-clnt-102924
The key's randomart image is:
+--[ RSA 2048]----+
|       ..oo .    |
|        o. o     |
|       ..        |
|      ..      .  |
|     .o.S. . . . |
|      .+o + . . .|
|        .o . . +E|
|             o* .|
|            .++o.|
+-----------------+
You should now be able to use ssh/scp with your instances.
For example, try running:

  $ ssh login-node-useast.us-east1-c.gbsc-gcp-project-scgs-dev

No config file found; using defaults

PLAYBOOK: gcloud_create_bucket.yml *********************************************
1 plays in /home/s0194353/loom/loom/playbooks/gcloud_create_bucket.yml

PLAY [Create a Google Cloud Storage bucket.] ***********************************

TASK [Create storage bucket. Ignore error if bucket already exists.] ***********
task path: /home/s0194353/loom/loom/playbooks/gcloud_create_bucket.yml:9
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0194353
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472578346.17-18988790854360 `" && echo ansible-tmp-1472578346.17-18988790854360="` echo $HOME/.ansible/tmp/ansible-tmp-1472578346.17-18988790854360 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp358FpH TO /home/s0194353/.ansible/tmp/ansible-tmp-1472578346.17-18988790854360/command
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /home/s0194353/env/bin/python /home/s0194353/.ansible/tmp/ansible-tmp-1472578346.17-18988790854360/command; rm -rf "/home/s0194353/.ansible/tmp/ansible-tmp-1472578346.17-18988790854360/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "gsutil mb gs://gbsc-gcp-project-scgs-dev-loom/", "delta": "0:00:01.558737", "end": "2016-08-30 10:32:27.807296", "failed": true, "invocation": {"module_args": {"_raw_params": "gsutil mb gs://gbsc-gcp-project-scgs-dev-loom/", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-08-30 10:32:26.248559", "stderr": "Creating gs://gbsc-gcp-project-scgs-dev-loom/...\nServiceException: 409 Bucket gbsc-gcp-project-scgs-dev-loom already exists.", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

No config file found; using defaults

PLAYBOOK: gcloud_create_server.yml *********************************************
3 plays in /home/s0194353/loom/loom/playbooks/gcloud_create_server.yml

PLAY [Create a new instance for the Loom server.] ******************************

TASK [Create a boot disk with the same name as the server instance.] ***********
task path: /home/s0194353/loom/loom/playbooks/gcloud_create_server.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0194353
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472578354.0-217941289257358 `" && echo ansible-tmp-1472578354.0-217941289257358="` echo $HOME/.ansible/tmp/ansible-tmp-1472578354.0-217941289257358 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpsmCm1u TO /home/s0194353/.ansible/tmp/ansible-tmp-1472578354.0-217941289257358/gce_pd
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /home/s0194353/env/bin/python /home/s0194353/.ansible/tmp/ansible-tmp-1472578354.0-217941289257358/gce_pd; rm -rf "/home/s0194353/.ansible/tmp/ansible-tmp-1472578354.0-217941289257358/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"changed": true, "disk_type": "pd-ssd", "image": "centos-7", "invocation": {"module_args": {"credentials_file": null, "detach_only": null, "disk_type": "pd-ssd", "image": "centos-7", "instance_name": null, "mode": "READ_WRITE", "name": "t-lm-srvr-102924", "pem_file": null, "project_id": null, "service_account_email": null, "size_gb": "163", "snapshot": null, "state": "present", "zone": "us-central1-a"}, "module_name": "gce_pd"}, "name": "t-lm-srvr-102924", "size_gb": 163, "state": "present", "zone": "us-central1-a"}

TASK [Boot up a new instance using the just-created boot disk.] ****************
task path: /home/s0194353/loom/loom/playbooks/gcloud_create_server.yml:19
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0194353
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472578361.42-91813427396239 `" && echo ansible-tmp-1472578361.42-91813427396239="` echo $HOME/.ansible/tmp/ansible-tmp-1472578361.42-91813427396239 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp4vCSr5 TO /home/s0194353/.ansible/tmp/ansible-tmp-1472578361.42-91813427396239/gce
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /home/s0194353/env/bin/python /home/s0194353/.ansible/tmp/ansible-tmp-1472578361.42-91813427396239/gce; rm -rf "/home/s0194353/.ansible/tmp/ansible-tmp-1472578361.42-91813427396239/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"changed": true, "instance_data": [{"disks": ["t-lm-srvr-102924"], "image": "centos-7-v20160803", "machine_type": "n1-standard-1", "metadata": {}, "name": "t-lm-srvr-102924", "network": "loom-legacy-network", "private_ip": "10.128.0.16", "public_ip": "104.154.225.19", "status": "RUNNING", "tags": ["loom-server", "http-server", "https-server", "loom-server-uscentral"], "zone": "us-central1-a"}], "invocation": {"module_args": {"credentials_file": null, "disk_auto_delete": true, "disks": ["t-lm-srvr-102924"], "external_ip": "ephemeral", "image": "debian-7", "instance_names": null, "ip_forward": false, "machine_type": "n1-standard-1", "metadata": null, "name": "t-lm-srvr-102924", "network": "loom-legacy-network", "pem_file": null, "persistent_boot_disk": false, "preemptible": null, "project_id": null, "service_account_email": null, "service_account_permissions": ["cloud-platform"], "state": "present", "tags": ["loom-server", "http-server", "https-server", "loom-server-uscentral"], "zone": "us-central1-a"}, "module_name": "gce"}, "name": "t-lm-srvr-102924", "state": "present", "zone": "us-central1-a"}

TASK [Wait for SSH to come up.] ************************************************
task path: /home/s0194353/loom/loom/playbooks/gcloud_create_server.yml:22
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0194353
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472578387.78-60385148214106 `" && echo ansible-tmp-1472578387.78-60385148214106="` echo $HOME/.ansible/tmp/ansible-tmp-1472578387.78-60385148214106 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp0UkYoy TO /home/s0194353/.ansible/tmp/ansible-tmp-1472578387.78-60385148214106/wait_for
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /home/s0194353/env/bin/python /home/s0194353/.ansible/tmp/ansible-tmp-1472578387.78-60385148214106/wait_for; rm -rf "/home/s0194353/.ansible/tmp/ansible-tmp-1472578387.78-60385148214106/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => (item={u'status': u'RUNNING', u'network': u'loom-legacy-network', u'zone': u'us-central1-a', u'tags': [u'loom-server', u'http-server', u'https-server', u'loom-server-uscentral'], u'image': u'centos-7-v20160803', u'disks': [u't-lm-srvr-102924'], u'name': u't-lm-srvr-102924', u'public_ip': u'104.154.225.19', u'private_ip': u'10.128.0.16', u'machine_type': u'n1-standard-1', u'metadata': {}}) => {"changed": false, "elapsed": 10, "invocation": {"module_args": {"connect_timeout": 5, "delay": 10, "exclude_hosts": null, "host": "10.128.0.16", "path": null, "port": 22, "search_regex": null, "state": "started", "timeout": 60}, "module_name": "wait_for"}, "item": {"disks": ["t-lm-srvr-102924"], "image": "centos-7-v20160803", "machine_type": "n1-standard-1", "metadata": {}, "name": "t-lm-srvr-102924", "network": "loom-legacy-network", "private_ip": "10.128.0.16", "public_ip": "104.154.225.19", "status": "RUNNING", "tags": ["loom-server", "http-server", "https-server", "loom-server-uscentral"], "zone": "us-central1-a"}, "path": null, "port": 22, "search_regex": null, "state": "started"}

TASK [Add host to new_instances.] **********************************************
task path: /home/s0194353/loom/loom/playbooks/gcloud_create_server.yml:25
creating host via 'add_host': hostname=10.128.0.16
changed: [localhost] => (item={u'status': u'RUNNING', u'network': u'loom-legacy-network', u'zone': u'us-central1-a', u'tags': [u'loom-server', u'http-server', u'https-server', u'loom-server-uscentral'], u'image': u'centos-7-v20160803', u'disks': [u't-lm-srvr-102924'], u'name': u't-lm-srvr-102924', u'public_ip': u'104.154.225.19', u'private_ip': u'10.128.0.16', u'machine_type': u'n1-standard-1', u'metadata': {}}) => {"add_host": {"groups": ["new_instances"], "host_name": "10.128.0.16", "host_vars": {}}, "changed": true, "invocation": {"module_args": {"groupname": "new_instances", "hostname": "10.128.0.16"}, "module_name": "add_host"}, "item": {"disks": ["t-lm-srvr-102924"], "image": "centos-7-v20160803", "machine_type": "n1-standard-1", "metadata": {}, "name": "t-lm-srvr-102924", "network": "loom-legacy-network", "private_ip": "10.128.0.16", "public_ip": "104.154.225.19", "status": "RUNNING", "tags": ["loom-server", "http-server", "https-server", "loom-server-uscentral"], "zone": "us-central1-a"}}

PLAY [Set up the Loom server on the new instance.] *****************************

TASK [setup] *******************************************************************
<10.128.0.16> ESTABLISH SSH CONNECTION FOR USER: None
<10.128.0.16> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/s0194353/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/s0194353/.ansible/cp/ansible-ssh-%h-%p-%r 10.128.0.16 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472578398.26-265139514786744 `" && echo ansible-tmp-1472578398.26-265139514786744="` echo $HOME/.ansible/tmp/ansible-tmp-1472578398.26-265139514786744 `" ) && sleep 0'"'"''
fatal: [10.128.0.16]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
	to retry, use: --limit @/home/s0194353/loom/loom/playbooks/gcloud_create_server.retry

PLAY RECAP *********************************************************************
10.128.0.16                : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=4    changed=3    unreachable=0    failed=0   

Creating or updating ~/.loom/gce.ini...
Creating ~/.loom/gce_key.json...
Creating deploy settings /home/s0194353/.loom/gcloud_deploy_settings.ini using user settings /home/s0194353/testsettings.ini...
Configuring SSH keys for gcloud...
```

**Comment by nhammond** [comment]
I see the same error when starting the server manually from my laptop. Here is the verbose output.
Immediately following, I was able to ssh to the machine, and able to successfully execute the failed ssh command listed in the output.

loom server create --settings ~/settings.ini --verbose
Your active configuration is: [default]

Your active configuration is: [default]

Creating deploy settings /Users/s0198839/.loom/gcloud_deploy_settings.ini using user settings /Users/s0198839/settings.ini...
Configuring SSH keys for gcloud...
You should now be able to use ssh/scp with your instances.
For example, try running:

  $ ssh login-node-useast.us-east1-c.gbsc-gcp-project-scgs-dev

No config file found; using defaults

PLAYBOOK: gcloud_create_bucket.yml *********************************************
1 plays in /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_bucket.yml

PLAY [Create a Google Cloud Storage bucket.] ***********************************

TASK [Create storage bucket. Ignore error if bucket already exists.] ***********
task path: /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_bucket.yml:9
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0198839
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472593701.16-252505038047793 `" && echo ansible-tmp-1472593701.16-252505038047793="` echo $HOME/.ansible/tmp/ansible-tmp-1472593701.16-252505038047793 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/30/xc7q6bkj1f75zp82j4cdy59mc3nhyw/T/tmpkZj5Ix TO /Users/s0198839/.ansible/tmp/ansible-tmp-1472593701.16-252505038047793/command
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /Users/s0198839/work/loom/env/bin/python /Users/s0198839/.ansible/tmp/ansible-tmp-1472593701.16-252505038047793/command; rm -rf "/Users/s0198839/.ansible/tmp/ansible-tmp-1472593701.16-252505038047793/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "gsutil mb gs://gbsc-gcp-project-scgs-dev-loom/", "delta": "0:00:02.191309", "end": "2016-08-30 14:48:23.630603", "failed": true, "invocation": {"module_args": {"_raw_params": "gsutil mb gs://gbsc-gcp-project-scgs-dev-loom/", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-08-30 14:48:21.439294", "stderr": "Creating gs://gbsc-gcp-project-scgs-dev-loom/...\nServiceException: 409 Bucket gbsc-gcp-project-scgs-dev-loom already exists.", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

No config file found; using defaults

PLAYBOOK: gcloud_create_server.yml *********************************************
3 plays in /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_server.yml

PLAY [Create a new instance for the Loom server.] ******************************

TASK [Create a boot disk with the same name as the server instance.] ***********
task path: /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_server.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0198839
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472593721.04-157530988020106 `" && echo ansible-tmp-1472593721.04-157530988020106="` echo $HOME/.ansible/tmp/ansible-tmp-1472593721.04-157530988020106 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/30/xc7q6bkj1f75zp82j4cdy59mc3nhyw/T/tmpCnza6A TO /Users/s0198839/.ansible/tmp/ansible-tmp-1472593721.04-157530988020106/gce_pd
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /Users/s0198839/work/loom/env/bin/python /Users/s0198839/.ansible/tmp/ansible-tmp-1472593721.04-157530988020106/gce_pd; rm -rf "/Users/s0198839/.ansible/tmp/ansible-tmp-1472593721.04-157530988020106/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"changed": true, "disk_type": "pd-ssd", "image": "centos-7", "invocation": {"module_args": {"credentials_file": null, "detach_only": null, "disk_type": "pd-ssd", "image": "centos-7", "instance_name": null, "mode": "READ_WRITE", "name": "test-skip-install2", "pem_file": null, "project_id": null, "service_account_email": null, "size_gb": "163", "snapshot": null, "state": "present", "zone": "us-central1-a"}, "module_name": "gce_pd"}, "name": "test-skip-install2", "size_gb": 163, "state": "present", "zone": "us-central1-a"}

TASK [Boot up a new instance using the just-created boot disk.] ****************
task path: /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_server.yml:19
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0198839
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472593728.03-165047192783533 `" && echo ansible-tmp-1472593728.03-165047192783533="` echo $HOME/.ansible/tmp/ansible-tmp-1472593728.03-165047192783533 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/30/xc7q6bkj1f75zp82j4cdy59mc3nhyw/T/tmpal1dlX TO /Users/s0198839/.ansible/tmp/ansible-tmp-1472593728.03-165047192783533/gce
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /Users/s0198839/work/loom/env/bin/python /Users/s0198839/.ansible/tmp/ansible-tmp-1472593728.03-165047192783533/gce; rm -rf "/Users/s0198839/.ansible/tmp/ansible-tmp-1472593728.03-165047192783533/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"changed": true, "instance_data": [{"disks": ["test-skip-install2"], "image": "centos-7-v20160803", "machine_type": "n1-standard-1", "metadata": {}, "name": "test-skip-install2", "network": "loom-legacy-network", "private_ip": "10.128.0.11", "public_ip": "104.198.225.176", "status": "RUNNING", "tags": ["test"], "zone": "us-central1-a"}], "invocation": {"module_args": {"credentials_file": null, "disk_auto_delete": true, "disks": ["test-skip-install2"], "external_ip": "ephemeral", "image": "debian-7", "instance_names": null, "ip_forward": false, "machine_type": "n1-standard-1", "metadata": null, "name": "test-skip-install2", "network": "loom-legacy-network", "pem_file": null, "persistent_boot_disk": false, "preemptible": null, "project_id": null, "service_account_email": null, "service_account_permissions": ["cloud-platform"], "state": "present", "tags": ["test"], "zone": "us-central1-a"}, "module_name": "gce"}, "name": "test-skip-install2", "state": "present", "zone": "us-central1-a"}

TASK [Wait for SSH to come up.] ************************************************
task path: /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_server.yml:22
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: s0198839
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472593754.4-62552849737313 `" && echo ansible-tmp-1472593754.4-62552849737313="` echo $HOME/.ansible/tmp/ansible-tmp-1472593754.4-62552849737313 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/30/xc7q6bkj1f75zp82j4cdy59mc3nhyw/T/tmpN6Rgma TO /Users/s0198839/.ansible/tmp/ansible-tmp-1472593754.4-62552849737313/wait_for
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /Users/s0198839/work/loom/env/bin/python /Users/s0198839/.ansible/tmp/ansible-tmp-1472593754.4-62552849737313/wait_for; rm -rf "/Users/s0198839/.ansible/tmp/ansible-tmp-1472593754.4-62552849737313/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => (item={u'status': u'RUNNING', u'network': u'loom-legacy-network', u'zone': u'us-central1-a', u'tags': [u'test'], u'image': u'centos-7-v20160803', u'disks': [u'test-skip-install2'], u'name': u'test-skip-install2', u'public_ip': u'104.198.225.176', u'private_ip': u'10.128.0.11', u'machine_type': u'n1-standard-1', u'metadata': {}}) => {"changed": false, "elapsed": 11, "invocation": {"module_args": {"connect_timeout": 5, "delay": 10, "exclude_hosts": null, "host": "104.198.225.176", "path": null, "port": 22, "search_regex": null, "state": "started", "timeout": 60}, "module_name": "wait_for"}, "item": {"disks": ["test-skip-install2"], "image": "centos-7-v20160803", "machine_type": "n1-standard-1", "metadata": {}, "name": "test-skip-install2", "network": "loom-legacy-network", "private_ip": "10.128.0.11", "public_ip": "104.198.225.176", "status": "RUNNING", "tags": ["test"], "zone": "us-central1-a"}, "path": null, "port": 22, "search_regex": null, "state": "started"}

TASK [Add host to new_instances.] **********************************************
task path: /Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_server.yml:25
creating host via 'add_host': hostname=104.198.225.176
changed: [localhost] => (item={u'status': u'RUNNING', u'network': u'loom-legacy-network', u'zone': u'us-central1-a', u'tags': [u'test'], u'image': u'centos-7-v20160803', u'disks': [u'test-skip-install2'], u'name': u'test-skip-install2', u'public_ip': u'104.198.225.176', u'private_ip': u'10.128.0.11', u'machine_type': u'n1-standard-1', u'metadata': {}}) => {"add_host": {"groups": ["new_instances"], "host_name": "104.198.225.176", "host_vars": {}}, "changed": true, "invocation": {"module_args": {"groupname": "new_instances", "hostname": "104.198.225.176"}, "module_name": "add_host"}, "item": {"disks": ["test-skip-install2"], "image": "centos-7-v20160803", "machine_type": "n1-standard-1", "metadata": {}, "name": "test-skip-install2", "network": "loom-legacy-network", "private_ip": "10.128.0.11", "public_ip": "104.198.225.176", "status": "RUNNING", "tags": ["test"], "zone": "us-central1-a"}}

PLAY [Set up the Loom server on the new instance.] *****************************

TASK [setup] *******************************************************************
<104.198.225.176> ESTABLISH SSH CONNECTION FOR USER: None
<104.198.225.176> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/s0198839/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/s0198839/.ansible/cp/ansible-ssh-%h-%p-%r 104.198.225.176 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472593766.22-222967945699935 `" && echo ansible-tmp-1472593766.22-222967945699935="` echo $HOME/.ansible/tmp/ansible-tmp-1472593766.22-222967945699935 `" ) && sleep 0'"'"''
fatal: [104.198.225.176]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
	to retry, use: --limit @/Users/s0198839/work/loom/loom/loom/playbooks/gcloud_create_server.retry

PLAY RECAP *********************************************************************
104.198.225.176            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=4    changed=3    unreachable=0    failed=0

**Comment by nhammond** [comment]
Settings used in the above comment:

[gcloud]
SERVER_TAGS = test
WORKER_TAGS = test
DOCKER_TAG = skip-worker-installs
WORKER_VM_IMAGE = loom-worker-centos7
WORKER_SKIP_INSTALLS = True
DOCKER_TAG = development
SERVER_NETWORK = loom-legacy-network

**Comment by nhammond** [comment]
Same settings worked on my next attempt. Can we add retries?

**Comment by isaacliao** [comment]
Added retries: 252714cd123f1bdd2cff55c2f4f6d038cd87691c

However, after further investigation, both this and the previous wait_for only check if the SSH port (tcp 22) is open. Doesn't actually verify that SSH connection is successful. I'll look for a way to do that.

**Comment by isaacliao** [comment]
Submitted a pull request: 0c3b3e9b746ef68fb15506a0c2a4cdaef1689ca7

In addition to checking if the port is open, this checks if the port contains the string "OpenSSH". This should mean that the host is ready to accept SSH connections.

**Comment by nhammond** [comment]
Closing, because I believe this issue was addressed. Similar ssh sporadic failure was introduced by instance metadata ssh keys #216 . Opened as separate issue #217.
