### ISSUE TITLE
setup.py dependency cleanup 

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#190]
Some dependencies listed in install_requires aren't directly used by Loom. We should remove these and let pip gather dependencies from the packages that need them, so that we don't prematurely install the wrong version (pip doesn't downgrade packages it has already installed).

Also, when searching for unused packages, remember that the PyPI name and the Python import name can be different. For instance, "google-api-python-client" vs. "googleapiclient".

**Comment by nhammond** [comment]
I trimmed setup.py to a minimal list, moved full list of dependencies to requirements.txt and updated install instructions (https://github.com/StanfordBioinformatics/loom/wiki/Installation) to use requirements.txt. 5b967cf
