### ISSUE TITLE
Loom server database migration silently failing

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#193]
Starting a loom server with MySQL certificate authentication. Have verified that this build runs on gcloud with MySQL. However, in this instance, observed behavior is that the "loom" docker container on the server restarts every 20 seconds.

The only logged output is to loom_django, but this shows only migration in progress and does not record any errors.

Running "docker log loom" shows unlogged errors (following comment).

**Comment by nhammond** [comment]
PLAY [Set up a loom user that Ansible will use to talk to the worker instance, since SSH login as root is disabled.] ***

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create a local loom user.] ***********************************************
ok: [localhost]

TASK [Generate ssh keys for the loom user. Overwrite if asked.] ****************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "echo -e 'y\\n' | ssh-keygen -q -t rsa -f ~/.ssh/google_compute_engine -P \"\"", "delta": "0:00:00.187884", "end": "2016-08-31 22:57:26.127404", "failed": true, "rc": 1, "start": "2016-08-31 22:57:25.939520", "stderr": "", "stdout": "/home/loom/.ssh/google_compute_engine already exists.\nOverwrite (y/n)? ", "stdout_lines": ["/home/loom/.ssh/google_compute_engine already exists.", "Overwrite (y/n)? "], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/opt/loom/loom/playbooks/gcloud_setup_loom_user.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

Traceback (most recent call last):
  File "/opt/loom/loom/master/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/loom/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/loom/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/loom/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/loom/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/loom/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/opt/loom/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/loom/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/loom/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1050, "Table 'analysis_abstractworkflow' already exists")
Traceback (most recent call last):
  File "/opt/loom/bin/loom", line 11, in <module>
Welcome to Loom!
Initializing database for first use...
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/opt/loom/loom/client/main.py", line 72, in main
    Main().run()
  File "/opt/loom/loom/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/opt/loom/loom/client/server.py", line 187, in start
    env = self._set_database(env)
  File "/opt/loom/loom/client/server.py", line 357, in _set_database
    msg += stdout[0]
UnboundLocalError: local variable 'stdout' referenced before assignment

**Comment by nhammond** [comment]
Based on above output, an error was detected after running migration (either nonzero return code or the word "error" was detected in stderr/stdout), but the error message was not logged due to a bug in the error message code.

**Comment by nhammond** [comment]
Interactive migration succeeds:

[root@loom-server-lndemo log]# docker exec -t loom /opt/loom/loom/master/manage.py showmigrations
analysis
 [ ] 0001_initial
 [ ] 0002_auto_20160825_1754
auth
 [ ] 0001_initial
 [ ] 0002_alter_permission_name_max_length
 [ ] 0003_alter_user_email_max_length
 [ ] 0004_alter_user_username_opts
 [ ] 0005_alter_user_last_login_null
 [ ] 0006_require_contenttypes_0002
contenttypes
 [ ] 0001_initial
 [ ] 0002_remove_content_type_name
sessions
 [ ] 0001_initial
[root@loom-server-lndemo log]# docker exec -t loom /opt/loom/loom/master/manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: corsheaders, staticfiles, messages, django_extensions, rest_framework, polymorphic
  Apply all migrations: contenttypes, auth, analysis, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table corsheaders_corsmodel
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...[root@loom-server-lndemo log]# docker exec -t loom /opy migrateom/master/manage.p
Operations to perform:
  Synchronize unmigrated apps: corsheaders, staticfiles, messages, django_extensions, rest_framework, polymorphic
  Apply all migrations: contenttypes, auth, analysis, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying analysis.0001_initial... OK
  Applying analysis.0002_auto_20160825_1754... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK
[root@loom-server-lndemo log]# 
[root@loom-server-lndemo log]# 
[root@loom-server-lndemo log]# docker exec -t loom /opt/loom/loom/master/manage.py showmigrations
analysis
 [X] 0001_initial
 [X] 0002_auto_20160825_1754
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
sessions
 [X] 0001_initial

**Comment by nhammond** [comment]
Another error seen in "docker log loom" looks like failure to overwrite existing ssh keys for loom user, error below. I tried manually removing keys with "docker exec loom rm /home/loom/.ssh/google_compute_engine /home/loom/.ssh/google_compute_engine.pub"


PLAY [Set up a loom user that Ansible will use to talk to the worker instance, since SSH login as root is disabled.] ***

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create a local loom user.] ***********************************************
ok: [localhost]

TASK [Generate ssh keys for the loom user. Overwrite if asked.] ****************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "echo -e 'y\\n' | ssh-keygen -q -t rsa -f ~/.ssh/google_compute_engine -P \"\"", "delta": "0:00:00.056586", "end": "2016-08-31 23:11:51.159242", "failed": true, "rc": 1, "start": "2016-08-31 23:11:51.102656", "stderr": "", "stdout": "/home/loom/.ssh/google_compute_engine already exists.\nOverwrite (y/n)? ", "stdout_lines": ["/home/loom/.ssh/google_compute_engine already exists.", "Overwrite (y/n)? "], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/opt/loom/loom/playbooks/gcloud_setup_loom_user.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by isaacliao** [comment]
Yeah, that last error is related to this issue: https://github.com/StanfordBioinformatics/loom/issues/127

We should add a step before that to delete keys in /home/loom/.ssh if they exist.

For now, you can remove the container entirely with "docker rm -f loom", then run "loom server start" again.

**Comment by nhammond** [comment]
Closing along with #127, resolved by #216
