### ISSUE TITLE
ansible fails to install docker-py

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#205]
This appears to be a bug in the ansible docker_container module exposed by a recent upgrade of docker-py from 1.9.x to 1.10.x.

This happens consistently when the gcloud_start_server playbook runs:

fatal: [10.128.0.13]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"api_version": "auto", "archive_path": null, "cacert_path": null, "cert_path": null, "container_limits": null, "debug": false, "docker_host": null, "dockerfile": null, "filter_logger": false, "force": true, "http_timeout": null, "key_path": null, "load_path": null, "name": "loomengine/loom:development", "nocache": "False", "path": null, "pull": true, "repository": null, "rm": true, "ssl_version": null, "state": "present", "tag": "development", "timeout": null, "tls": null, "tls_hostname": null, "tls_verify": null, "use_tls": "no"}, "module_name": "docker_image"}, "msg": "Error: docker-py version is 1.10.2. Minimum version required is 1.7.0."}

**Comment by isaacliao** [comment]
Yup: https://github.com/ansible/ansible/issues/17495

Fixed in Ansible dev branch: https://github.com/ansible/ansible/pull/17496

**Comment by isaacliao** [comment]
Fixed in af21aca
