### ISSUE TITLE
Reduce default boot disk size

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#218]
Currently we have both a boot disk and a persistent disk. Each defaults to 163 GB SSD.

Since Google throttles IO speed to an instance according to its persistent disk size, there is a clear case for using the 163 GB default size on the persistent disk (https://cloud.google.com/compute/docs/disks/performance). 

But it's not clear that we benefit from a large boot disk.

**Comment by isaacliao** [comment]
Hmm, I think boot disks are persistent disks? At least, I don't see the option to create an instance with a local SSD instead of a persistent disk.

**Comment by isaacliao** [comment]
Reduced to 50 GB in 7714ce2493ad438bbdec9b47d7334657a741a63a
