### ISSUE TITLE
Loom install fails with EnvironmentError: mysql_config not found

### ISSUE THREAD

**Issue by pbilling** [StanfordBioinformatics/loom#220]
When I tried using the "pip install loomengine" to install loom on my mac, the install died with "EnvironmentError: mysql_config not found". I was able to resolve the issue by first doing "brew install mysql"; solution found here: 

http://stackoverflow.com/questions/25459386/mac-os-x-environmenterror-mysql-config-not-found

![screen shot 2016-10-25 at 11 08 07 am](https://cloud.githubusercontent.com/assets/14796101/19698611/d6b1e7f4-9aa4-11e6-93bd-e514dda0dda6.png)

**Comment by isaacliao** [comment]
Thanks for reporting this, Paul! Yeah, we keep going back and forth on whether to include MySQL as a Python dependency for Loom. It is for the server, but not the client, and eventually when we separate the components, this will stop being an issue.

**Comment by nhammond** [comment]
Closing as a duplicate with #203, which covers breaking the client out so its install requirements won't include MySQL.
