### ISSUE TITLE
Loom could not connect to its database

### ISSUE THREAD

**Issue by pbilling** [StanfordBioinformatics/loom#226]
When trying to run Loom locally, I ran into "Exception: Loom could not connect to its database. Exiting now."

$ loom server set local
$ loom server create
$ loom server start
Traceback (most recent call last):
  File "/usr/local/bin/loom", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/loom/client/main.py", line 72, in main
    Main().run()
  File "/Library/Python/2.7/site-packages/loom/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/Library/Python/2.7/site-packages/loom/client/server.py", line 187, in start
    env = self._set_database(env)
  File "/Library/Python/2.7/site-packages/loom/client/server.py", line 346, in _set_database
    raise Exception(msg)
Exception: Loom could not connect to its database. Exiting now.
$ loom version
client version: 0.1.5
server version: unavailable

[local_deploy_settings.txt](https://github.com/StanfordBioinformatics/loom/files/552040/local_deploy_settings.txt)
[nginx.txt](https://github.com/StanfordBioinformatics/loom/files/552041/nginx.txt)
[server.txt](https://github.com/StanfordBioinformatics/loom/files/552042/server.txt)
[settings.txt](https://github.com/StanfordBioinformatics/loom/files/552043/settings.txt)

**Comment by pbilling** [comment]
I also tried setting up a local server using the "Installing from pip using virtualenv (recommended)" steps and ran into the same issue.

**Comment by nhammond** [comment]
Caused by conflicts between virtualenv and PYTHONPATH. No changes, except install instructions now say to blank out PYTHONPATH. https://github.com/StanfordBioinformatics/loom/wiki/Installation
