### ISSUE TITLE
Docker containers fill boot disk, not scratch disk, on gcloud vms

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#236]
Containers occupy disk space here:
/var/lib/docker/

which is on the boot disk, not the scratch disk.

If I have a run with a very large scratch disk, and the process writes to /tmp or something other than the working directory, I risk filling up the boot disk, and increasing the worker scratch disk size will not prevent failure.

**Comment by nhammond** [comment]
Simplest solution is to create a single disk, the boot disk, such that docker containers and images use memory there.

An addional possibility is to create a ramdisk and mounting it to /tmp, but this gives another degree of freedom to users, the ramdisk and requested memory would have to be sized compatibly.

**Comment by isaacliao** [comment]
You can also specify a larger boot disk size with a setting:
```
WORKER_BOOT_DISK_SIZE: 163
```
