### ISSUE TITLE
Sporadic failure on ansible yum install pip on worker nodes

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#249]
This was observed in an automated test running "hello_world". Appears to be sporadic, since one step had completed successfully, and a later manual run completed all 3 steps succesfully.

TASK [Read SSH key and create a metadata file from it] *************************
task path: /opt/loom/loomengine/playbooks/tasks/gcloud_configure_instance_ssh.yml:3
Using module file /opt/loom/local/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1480049291.12-88194795352381 `" && echo ansible-tmp-1480049291.12-88194795352381="` echo $HOME/.ansible/tmp/ansible-tmp-1480049291.12-88194795352381 `" ) && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "append": false, 
            "comment": null, 
            "createhome": true, 
            "expires": null, 
            "force": false, 
            "generate_ssh_key": true, 
            "group": null, 
            "groups": null, 
            "home": null, 
            "login_class": null, 
            "move_home": false, 
--
            "update_cache": true, 
            "validate_certs": true
        }, 
        "module_name": "yum"
    }, 
    "msg": "warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY\nImporting GPG key 0x2C52609D:\n Userid     : \"Docker Release Tool (releasedocker) <docker@docker.com>\"\n Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d\n From       : https://yum.dockerproject.org/gpg\nNon-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.3-1.el7.centos.noarch\n", 
    "rc": 0, 
    "results": [
        "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.steadfast.net\n * extras: mirror.team-cymru.org\n * updates: chicago.gaminghost.co\nResolving Dependencies\n--> Running transaction check\n---> Package docker-engine.x86_64 0:1.12.3-1.el7.centos will be installed\n--> Processing Dependency: docker-engine-selinux >= 1.12.3-1.el7.centos for package: docker-engine-1.12.3-1.el7.centos.x86_64\n--> Processing Dependency: libcgroup for package: docker-engine-1.12.3-1.el7.centos.x86_64\n--> Processing Dependency: libseccomp.so.2()(64bit) for package: docker-engine-1.12.3-1.el7.centos.x86_64\n--> Processing Dependency: libltdl.so.7()(64bit) for package: docker-engine-1.12.3-1.el7.centos.x86_64\n--> Running transaction check\n---> Package docker-engine-selinux.noarch 0:1.12.3-1.el7.centos will be installed\n--> Processing Dependency: policycoreutils-python for package: docker-engine-selinux-1.12.3-1.el7.centos.noarch\n---> Package libcgroup.x86_64 0:0.41-8.el7 will be installed\n---> Package libseccomp.x86_64 0:2.2.1-1.el7 will be installed\n---> Package libtool-ltdl.x86_64 0:2.4.2-21.el7_2 will be installed\n--> Running transaction check\n---> Package policycoreutils-python.x86_64 0:2.2.5-20.el7 will be installed\n--> Processing Dependency: libsemanage-python >= 2.1.10-1 for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: audit-libs-python >= 2.1.3-4 for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: python-IPy for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: libqpol.so.1(VERS_1.4)(64bit) for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: libqpol.so.1(VERS_1.2)(64bit) for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: libapol.so.4(VERS_4.0)(64bit) for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: checkpolicy for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: libqpol.so.1()(64bit) for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Processing Dependency: libapol.so.4()(64bit) for package: policycoreutils-python-2.2.5-20.el7.x86_64\n--> Running transaction check\n---> Package audit-libs-python.x86_64 0:2.4.1-5.el7 will be installed\n---> Package checkpolicy.x86_64 0:2.1.12-6.el7 will be installed\n---> Package libsemanage-python.x86_64 0:2.1.10-18.el7 will be installed\n---> Package python-IPy.noarch 0:0.75-6.el7 will be installed\n---> Package setools-libs.x86_64 0:3.3.7-46.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                 Arch    Version                Repository         Size\n================================================================================\nInstalling:\n docker-engine           x86_64  1.12.3-1.el7.centos    docker-main-repo   19 M\nInstalling for dependencies:\n audit-libs-python       x86_64  2.4.1-5.el7            base               69 k\n checkpolicy             x86_64  2.1.12-6.el7           base              247 k\n docker-engine-selinux   noarch  1.12.3-1.el7.centos    docker-main-repo   28 k\n libcgroup               x86_64  0.41-8.el7             base               64 k\n libseccomp              x86_64  2.2.1-1.el7            base               49 k\n libsemanage-python      x86_64  2.1.10-18.el7          base               94 k\n libtool-ltdl            x86_64  2.4.2-21.el7_2         updates            49 k\n policycoreutils-python  x86_64  2.2.5-20.el7           base              435 k\n python-IPy              noarch  0.75-6.el7             base               32 k\n setools-libs            x86_64  3.3.7-46.el7           base              485 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+10 Dependent packages)\n\nTotal download size: 21 M\nInstalled size: 84 M\nDownloading packages:\nPublic key for docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm is not installed\n--------------------------------------------------------------------------------\nTotal                                               15 MB/s |  21 MB  00:01     \nRetrieving key from https://yum.dockerproject.org/gpg\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Installing : libcgroup-0.41-8.el7.x86_64                                 1/11 \n  Installing : audit-libs-python-2.4.1-5.el7.x86_64                        2/11 \n  Installing : libsemanage-python-2.1.10-18.el7.x86_64                     3/11 \n  Installing : libseccomp-2.2.1-1.el7.x86_64                               4/11 \n  Installing : python-IPy-0.75-6.el7.noarch                                5/11 \n  Installing : checkpolicy-2.1.12-6.el7.x86_64                             6/11 \n  Installing : libtool-ltdl-2.4.2-21.el7_2.x86_64                          7/11 \n  Installing : setools-libs-3.3.7-46.el7.x86_64                            8/11 \n  Installing : policycoreutils-python-2.2.5-20.el7.x86_64                  9/11 \n  Installing : docker-engine-selinux-1.12.3-1.el7.centos.noarch           10/11 \nrestorecon:  lstat(/var/lib/docker) failed:  No such file or directory\nwarning: %post(docker-engine-selinux-1.12.3-1.el7.centos.noarch) scriptlet failed, exit status 255\n  Installing : docker-engine-1.12.3-1.el7.centos.x86_64                   11/11 \n  Verifying  : setools-libs-3.3.7-46.el7.x86_64                            1/11 \n  Verifying  : libcgroup-0.41-8.el7.x86_64                                 2/11 \n  Verifying  : libtool-ltdl-2.4.2-21.el7_2.x86_64                          3/11 \n  Verifying  : docker-engine-1.12.3-1.el7.centos.x86_64                    4/11 \n  Verifying  : checkpolicy-2.1.12-6.el7.x86_64                             5/11 \n  Verifying  : python-IPy-0.75-6.el7.noarch                                6/11 \n  Verifying  : libseccomp-2.2.1-1.el7.x86_64                               7/11 \n  Verifying  : libsemanage-python-2.1.10-18.el7.x86_64                     8/11 \n  Verifying  : docker-engine-selinux-1.12.3-1.el7.centos.noarch            9/11 \n  Verifying  : policycoreutils-python-2.2.5-20.el7.x86_64                 10/11 \n  Verifying  : audit-libs-python-2.4.1-5.el7.x86_64                       11/11 \n\nInstalled:\n  docker-engine.x86_64 0:1.12.3-1.el7.centos                                    \n\nDependency Installed:\n  audit-libs-python.x86_64 0:2.4.1-5.el7                                        \n  checkpolicy.x86_64 0:2.1.12-6.el7                                             \n  docker-engine-selinux.noarch 0:1.12.3-1.el7.centos                            \n  libcgroup.x86_64 0:0.41-8.el7                                                 \n  libseccomp.x86_64 0:2.2.1-1.el7                                               \n  libsemanage-python.x86_64 0:2.1.10-18.el7                                     \n  libtool-ltdl.x86_64 0:2.4.2-21.el7_2                                          \n  policycoreutils-python.x86_64 0:2.2.5-20.el7                                  \n  python-IPy.noarch 0:0.75-6.el7                                                \n  setools-libs.x86_64 0:3.3.7-46.el7                                            \n\nComplete!\n"
    ]
}

**Comment by isaacliao** [comment]
Hmm, that step doesn't use yum: https://github.com/StanfordBioinformatics/loom/blob/customserviceaccounts/loomengine/playbooks/tasks/gcloud_configure_instance_ssh.yml#L4

Is it possible that the error message is interspersed with another step? I've seen that happen before when Ansible is executing on multiple worker nodes.

**Comment by nhammond** [comment]
You're right. The only yum step building a worker node is this. I saw a failure in this step when running interactively yesterday, as further evidence for a sporadic failure on yum install python-pip. Updating issue title to reflect.

```
  - name: Install pip, which is needed to install docker-py.
    yum: name=python-pip disable_gpg_check=yes update_cache=yes
    register: pipinstallresult
    retries: 10
    until: pipinstallresult['rc'] is defined and pipinstallresult['rc'] == 0
```

**Comment by nhammond** [comment]
Unclear what was happening here. May be related to the race condition with SSH key generation, which has been fixed. Closing unless it comes up again.
