### ISSUE TITLE
Error pulling docker image

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#250]
TASK [loom-master : Pull Docker image.] ****************************************
task path: /home/nhammond/dev/loom-scratch/loom/loomengine/playbooks/roles/loom-master/tasks/main.yml:13
Using module file /home/nhammond/dev/loom-scratch/env/local/lib/python2.7/site-packages/ansible/modules/core/cloud/docker/docker_image.py
<104.198.145.170> ESTABLISH SSH CONNECTION FOR USER: None
<104.198.145.170> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/nhammond/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nhammond/.ansible/cp/ansible-ssh-%h-%p-%r 104.198.145.170 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1480546732.07-229211885465603 `" && echo ansible-tmp-1480546732.07-229211885465603="` echo /tmp/ansible-tmp-1480546732.07-229211885465603 `" ) && sleep 0'"'"''
<104.198.145.170> PUT /tmp/tmp6yRaPP TO /tmp/ansible-tmp-1480546732.07-229211885465603/docker_image.py
<104.198.145.170> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/nhammond/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nhammond/.ansible/cp/ansible-ssh-%h-%p-%r '[104.198.145.170]'
<104.198.145.170> ESTABLISH SSH CONNECTION FOR USER: None
<104.198.145.170> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/nhammond/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nhammond/.ansible/cp/ansible-ssh-%h-%p-%r 104.198.145.170 '/bin/sh -c '"'"'setfacl -m u:loom:rx /tmp/ansible-tmp-1480546732.07-229211885465603/ /tmp/ansible-tmp-1480546732.07-229211885465603/docker_image.py && sleep 0'"'"''
<104.198.145.170> ESTABLISH SSH CONNECTION FOR USER: None
<104.198.145.170> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/nhammond/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nhammond/.ansible/cp/ansible-ssh-%h-%p-%r -tt 104.198.145.170 '/bin/sh -c '"'"'sudo -H -S -n -u loom /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-nofyvtkcwplxkczvjizfmabwveewhnxq; /usr/bin/python /tmp/ansible-tmp-1480546732.07-229211885465603/docker_image.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<104.198.145.170> ESTABLISH SSH CONNECTION FOR USER: None
<104.198.145.170> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/nhammond/.ssh/google_compute_engine"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nhammond/.ansible/cp/ansible-ssh-%h-%p-%r 104.198.145.170 '/bin/sh -c '"'"'rm -f -r /tmp/ansible-tmp-1480546732.07-229211885465603/ > /dev/null 2>&1 && sleep 0'"'"''
fatal: [104.198.145.170]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": "auto", 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": null, 
            "filter_logger": false, 
            "force": true, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "loomengine/loom:development", 
            "nocache": "False", 
            "path": null, 
            "pull": true, 
            "push": false, 
            "repository": null, 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "development", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
        }, 
        "module_name": "docker_image"
    }, 
    "msg": "Error pulling loomengine/loom - code: None message: Get http://: http: no Host in request URL"
}
	to retry, use: --limit @/home/nhammond/dev/loom-scratch/loom/loomengine/playbooks/gcloud_create_server.retry

**Comment by isaacliao** [comment]
Appears to be a new issue starting today. Others are seeing it as well: http://stackoverflow.com/questions/40895823/ansible-docker-container-no-host-in-request-url-docker-pull-works-correctly

Not sure what the cause is. I checked versions of Ansible, Docker, and docker-py, and no obvious recent changes there. Apparently a workaround (from link above) is to downgrade docker-compose, but this doesn't tell us what the root cause is.

**Comment by isaacliao** [comment]
Nate tracked this down to a new version of the requests module. Need to update Dockerfile to specify dependency versions and use requirements.txt: https://github.com/StanfordBioinformatics/loom/blob/development/Dockerfile

**Comment by nhammond** [comment]
Added ansible task to install requests prior to docker-py, locked down version 2.12.1. Also updated Dockerfile to pip install using -r requirements.txt in order to lock down versions of libraries not listed in setup.py. 9fc3326485a9a95437db2851b966a0fbfbfb1ffd
