### ISSUE TITLE
Need to differentiate between "Finished Successfully" and "Finished Unsuccessfully" task run statuses

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#253]
Currently task run status is set to "Finished" even if there was an exception running the task:

https://github.com/StanfordBioinformatics/loom/blob/workercleanup/loomengine/worker/task_runner.py#L88

Since we don't have a way to indicate "Finished with errors", this results in the worker VM getting cleaned up.

**Comment by nhammond** [comment]
Moved to boolean status flags with release 0.3.0, including "is_failed"
