### ISSUE TITLE
Require and log Docker image IDs for reproducibility

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#255]
Specifying a step using only a Docker image name and a tag is not sufficient to guarantee reproducibility, since tags can be subsequently remapped to point to a different version of the image. We should warn users or require a --force-nonreproducible flag to run a workflow that has underspecified Docker image identifiers. In both cases, we need to log Docker image IDs when running workflows, in order to have a record of which version of a Docker image that each step was run in.

However, the disadvantage of using only Docker image IDs is that they are not human-readable, and if an image ID becomes unavailable, figuring out which tag it was originally associated with (to update and fix the workflow) is nontrivial.

More details here: https://docs.google.com/document/d/1QPnCwaZddKEBJ8gFA80NA8h7domRlVrCWzTkZLWFzsw/edit?usp=sharing

**Comment by isaacliao** [comment]
Added in e5a39b8469af265fcf6f4d06d7398d54e95f95a3:

Docker image ID's now logged in worker output, and also in image_id field in TaskRunAttempt model:
```
INFO [2016-12-14 21:20:32,452] Initializing working directory /mnt/loomdata/runtime_volumes/b3cc835deb74447691c89684ae86ccd6/work
INFO [2016-12-14 21:20:32,452] Downloading input files
INFO [2016-12-14 21:20:32,626] Exporting file hello_cap.txt@f42fc8461d2e474d99b0bebfceb963da to file:///mnt/loomdata/runtime_volumes/b3cc835deb74447691c89684ae86ccd6/work/hello_cap.txt...
INFO [2016-12-14 21:20:32,941] ...finished exporting file
INFO [2016-12-14 21:20:32,963] Exporting file world_cap.txt@30c08c2db40a41678f56cbc1be409929 to file:///mnt/loomdata/runtime_volumes/b3cc835deb74447691c89684ae86ccd6/work/world_cap.txt...
INFO [2016-12-14 21:20:33,380] ...finished exporting file
INFO [2016-12-14 21:20:33,380] Creating run script
INFO [2016-12-14 21:20:36,045] Pulled image ubuntu:latest and received image id sha256:4ca3a192ff2a5b7e225e81dc006b6379c10776ed3619757a65608cb72de0a7f6
```

**Comment by nhammond** [comment]
Related to #19

**Comment by nhammond** [comment]
Currently saving container info as a JSON under TaskAttempt.environment_info. This includes the 'Id' field with image ID. 30cbbcbc9400c7ad42af2bf7fb8cd62f904ba46a
