### ISSUE TITLE
Loom dashboard should link directly to files in Google Storage

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#256]
Currently, to browse to a file in Google Storage, a user has to manually traverse the directory structure. This is not a good user experience, and could be fixed by providing a URL.

![screenshot 2016-12-14 14 09 13](https://cloud.githubusercontent.com/assets/1683569/21203366/00d35df4-c207-11e6-9f6c-2ef03b7e46a4.png)

**Comment by nhammond** [comment]
Duplicate of #52
