### ISSUE TITLE
Improve propagation of settings from client to other components

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#26]
Currently, the client loads settings, sets environment variables, and starts the Django server. The Django server reads settings from the environment variables and makes them available to components through the API (e.g. $MASTER_URL/api/workerinfo). 

However, there are several disadvantages to this approach:

- It doesn't work when the client and the webserver are on different machines. For example, if the client is a local laptop, and the webserver is in Elasticluster, environment variables aren't shared, so settings are not passed. Instead, one would need to modify the settings on the frontend node of Elasticluster, where the server is running, and then restart it.
- Adding a setting touches many different locations in the code. A new setting needs to be declared in "setting_keys_to_export" in settings_manager.py, the Django settings.py, views.py, and urls.py if it isn't part of an existing API info bundle.
- Settings are only read by the webserver at startup time. This means that some things need to happen before the server is started (e.g., Elasticluster running). Possibly not a disadvantage; this makes sense for some things that shouldn't be changed after the server is already running.

Proposal:

- The server should start in either a default or an uninitialized state, with the bare minimum of settings required to function. The client should then POST settings to the server. Other components should retrieve settings from the server using the REST API.
- Components should only need to know the server URL, and have HTTP access to it.

**Comment by nhammond** [comment]
Let's also consider how settings affect ease of use through pip. Default should allow use in a "private" mode, or auto-generate the secret key for django, so that no additional env variables are required to "loom server start" immediately after "pip install loomengine"

**Comment by isaacliao** [comment]
Implemented in 5d3c9efc96f876de68eb742f90e379fdb5b4e63d.
