### ISSUE TITLE
On CentOS, selinux package not found in virtualenv

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#269]
The error:
```PLAY [Create connection settings file now that we have a server IP.] ***********

TASK [Create connection settings file so client knows where to find server] ****
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```
However, that package is installed:
```
(loom-env) [iliao@cgs-demo-loom-client-no-ip-gcloudplaybooks ~]$ sudo yum install libselinux-python
Package libselinux-python-2.5-6.el7.x86_64 already installed and latest version
Nothing to do
```
Python in a virtualenv can't find it, but system Python can:
```
(loom-env) [iliao@cgs-demo-loom-client-no-ip-gcloudplaybooks ~]$ python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import selinux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named selinux
>>> 
(loom-env) [iliao@cgs-demo-loom-client-no-ip-gcloudplaybooks ~]$ deactivate
[iliao@cgs-demo-loom-client-no-ip-gcloudplaybooks ~]$ python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import selinux
>>>
```
Workaround is to copy `/usr/lib64/python2.7/site-packages/selinux` to `$VIRTUAL_ENV/lib/python2.7/site-packages`

Sources:

https://github.com/ansible/ansible/issues/13313
https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/

**Comment by nhammond** [comment]
Does "virtualenv --system-site-packages" work?

**Comment by isaacliao** [comment]
Yeah, I think that would work, but the downside is then you open yourself up to incompatible package versions from the system. From the second link:

> Okay, so if you inherit site packages, that solves the problem - you’ll get the selinux module in your virtual environment - along with the rest of the globally installed python modules that are installed. That’s a problem for me, I don’t want to pollute my virtual environments with site packages as they are used in jenkins jobs and could potentially have an effect on the jobs.

**Comment by isaacliao** [comment]
This issue also shows up when running `loom server start` from a newly-installed CentOS client.

**Comment by nhammond** [comment]
Ranjan hit this in testing. He is using the workaround of copying the selinux dir, and this works.

**Comment by nhammond** [comment]
I believe this is just a doc issue. It affects users running virtualenv on RedHat/Centos. It affects the installation process for Loom, but once Loom is installed it doesn't affect anything in how Loom runs.

**Comment by nhammond** [comment]
The workaround is in the doc here: https://loom.readthedocs.io/en/latest/installing.html#installing-prerequisites-on-centos-7
