### ISSUE TITLE
loom server start fails when optional gcloud settings are blank

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#288]
e.g. LOOM_GCLOUD_SERVER_SUBNETWORK should not be a required setting

**Comment by isaacliao** [comment]
Fixed in 856edd11ec04ed28c2267ceb8fd3afea4b5c0c78 by omitting Ansible module arguments when their value would be undefined, an empty string, a whitespace string, or any other "false-like" value.
