### ISSUE TITLE
Excluding "--admin-files" produces an unhelpful error

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#290]
When running on gcloud, with a service account key set in the conf file, "loom server start --settings ~/mysettings.conf" (forgetting to include --admin-files ~/my-admin-files) produces this:

Starting a Loom server named "nate-test2".
ERROR! Attempted to execute "/Users/s0198839/.loom/inventory/gce_wrapper.py" as inventory script: Inventory script (/Users/s0198839/.loom/inventory/gce_wrapper.py) had an execution error: Traceback (most recent call last):
  File "/Users/s0198839/.loom/inventory/gce_wrapper.py", line 26, in <module>
    with open(GCE_PEM_FILE_PATH, 'r') as f:
IOError: [Errno 2] No such file or directory: '/Users/s0198839/.loom/admin-files/nate-test-key.json'

**Comment by isaacliao** [comment]
Implemented in 68051a1ebac0466afe41757c5dda5b0a0ce75be7.
