### ISSUE TITLE
Save logs for create and cleanup of taskattempt as objects on that taskattempt

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#323]
Save logs for create and cleanup of taskattempt as objects on that taskattempt. Also save stdout/err of the taskrunner container on the taskattempt.

**Comment by isaacliao** [comment]
Taskrunner container stdout/stderr logs to fluentd as of b67a5d5706e794672515c9a3b832ce05f1dfca9f. Leaving open for the first part.

**Comment by isaacliao** [comment]
Renamed issue to reflect open part, so that I stop thinking I can close it.

**Comment by nhammond** [comment]
We have accomplished this with timepoints/events. These save progress messages and error messages to the TaskAttempt.
