### ISSUE TITLE
GoogleBaseError / backendError when creating scratch disk

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#324]
0197118.21-24187090889184 `\" && echo ansible-tmp-1490197118.21-24187090889184=\"` echo $HOME/.ansible/tmp/ansible-tmp-1490197118.21-24187090889184 `\" ) && sleep 0'\n<127.0.0.1> P\
UT /tmp/tmpLzONGq TO /root/.ansible/tmp/ansible-tmp-1490197118.21-24187090889184/setup.py\n<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1490197118.21-24187\
090889184/ /root/.ansible/tmp/ansible-tmp-1490197118.21-24187090889184/setup.py && sleep 0'\n<127.0.0.1> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1490197\
118.21-24187090889184/setup.py; rm -rf \"/root/.ansible/tmp/ansible-tmp-1490197118.21-24187090889184/\" > /dev/null 2>&1 && sleep 0'\nok: [localhost]\n\nTASK [Create a boot disk wi\
th the same name as the instance.] ******************\ntask path: /loom-settings/playbooks/tasks/gcloud_create_instance.yml:1\nUsing module file /usr/local/lib/python2.7/dist-packa\
ges/ansible/modules/core/cloud/google/gce_pd.py\n<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root\n<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p \"` echo $HOME/.ansible/\
tmp/ansible-tmp-1490197120.54-47079593406802 `\" && echo ansible-tmp-1490197120.54-47079593406802=\"` echo $HOME/.ansible/tmp/ansible-tmp-1490197120.54-47079593406802 `\" ) && slee\
p 0'\n<127.0.0.1> PUT /tmp/tmpH85uTI TO /root/.ansible/tmp/ansible-tmp-1490197120.54-47079593406802/gce_pd.py\n<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp\
-1490197120.54-47079593406802/ /root/.ansible/tmp/ansible-tmp-1490197120.54-47079593406802/gce_pd.py && sleep 0'\n<127.0.0.1> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tm\
p/ansible-tmp-1490197120.54-47079593406802/gce_pd.py; rm -rf \"/root/.ansible/tmp/ansible-tmp-1490197120.54-47079593406802/\" > /dev/null 2>&1 && sleep 0'\nfatal: [localhost]: FAIL\
ED! => {\n    \"changed\": false, \n    \"failed\": true, \n    \"invocation\": {\n        \"module_args\": {\n            \"credentials_file\": \"/loom-settings/admin-files/gce_ke\
y.json\", \n            \"detach_only\": null, \n            \"disk_type\": \"pd-standard\", \n            \"image\": \"compute-golden2\", \n            \"instance_name\": null, \n\
            \"mode\": \"READ_WRITE\", \n            \"name\": \"sowmi-loom3-server-mar-16-2017-223630-collectgcbia-23aa9af-work\", \n            \"pem_file\": null, \n            \\
"project_id\": \"gbsc-gcp-project-scgs-dev\", \n            \"service_account_email\": \"jenkins-loom-tester@gbsc-gcp-project-scgs-dev.iam.gserviceaccount.com\", \n            \"si\
ze_gb\": \"20\", \n            \"snapshot\": null, \n            \"state\": \"present\", \n            \"zone\": \"us-central1-a\"\n        }, \n        \"module_name\": \"gce_pd\"\
\n    }, \n    \"msg\": \"Unexpected response: ({u'domain': u'global', u'message': u\\\"Code: '6947857904367436757'\\\", u'reason': u'backendError'}). Detail: Traceback (most recen\
t call last):\\n  File \\\"/tmp/ansible_EltOr0/ansible_modlib.zip/ansible/module_utils/gcp.py\\\", line 105, in gcp_connect\\n    project=project_id)\\n  File \\\"/usr/local/lib/py\
thon2.7/dist-packages/libcloud/compute/drivers/gce.py\\\", line 1363, in __init__\\n    self.region_list = self.ex_list_regions()\\n  File \\\"/usr/local/lib/python2.7/dist-package\
s/libcloud/compute/drivers/gce.py\\\", line 1972, in ex_list_regions\\n    response = self.connection.request(request, method='GET').object\\n  File \\\"/usr/local/lib/python2.7/di\
st-packages/libcloud/compute/drivers/gce.py\\\", line 120, in request\\n    response = super(GCEConnection, self).request(*args, **kwargs)\\n  File \\\"/usr/local/lib/python2.7/dis\
t-packages/libcloud/common/google.py\\\", line 806, in request\\n    *args, **kwargs)\\n  File \\\"/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py\\\", line 862, in \
request\\n    response = responseCls(**kwargs)\\n  File \\\"/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py\\\", line 181, in __init__\\n    self.object = self.parse\
_body()\\n  File \\\"/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py\\\", line 294, in parse_body\\n    raise GoogleBaseError(message, self.status, code)\\nGoogleB\
aseError: {u'domain': u'global', u'message': u\\\"Code: '6947857904367436757'\\\", u'reason': u'backendError'}\\n\"\n}\n\tto retry, use: --limit @/loom-settings/playbooks/gcloud_ru\
n_task.retry\n\nPLAY RECAP *********************************************************************\nlocalhost                  : ok=7    changed=3    unreachable=0    failed=1   \n\n\
",

**Comment by nhammond** [comment]
Could be an invalid disk name? Server name is  sowmi-loom3-server-mar-16-2017-223630, and other taskattempts on this server were successful.

**Comment by isaacliao** [comment]
Hmm, the disk name looks fine:

    "name": "sowmi-loom3-server-mar-16-2017-223630-collectgcbia-23aa9af-work"

It's 63 characters, starts and ends with a lowercase letter, and only contains lowercase letters, numbers, and dashes.

> Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.

(From: https://cloud.google.com/compute/docs/reference/beta/disks)

Not sure what's causing this. It's failing at libcloud level, so might have to dig into that.

**Comment by nhammond** [comment]
Added retries here: 8b82f9f5c8bfb7f8ddf81717f9dfea7e61f1bb1b
