### ISSUE TITLE
Let fluentd server regex in ansible handle no port

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#332]
Suggesting a slight modification from regex for getting host name in loomengine/client/playbooks/tasks/run_task.yaml:

    '^.*://(.+)(?:.+)?$'

instead of 

    '^.*://(.+):.+$'

That still works if no port is specified. Tested in python but not in ansible.

**Comment by isaacliao** [comment]
Implemented in 0566e661ce86717886aa02eaddcba40cf771893a
