### ISSUE TITLE
Minimize required settings

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#334]
Wherever possible settings should have good default values and not be required in the config file. Since Loom is not aware of individual settings, defaults cannot be defined in the code. Defining a user-customizable defaults.ini file bloats the interface and could be confusing. Best solution is to define defaults at point of use--e.g., ansible playbooks that need a container name suffix will each have that suffix defined as default to take effect when no setting is given. This badly violates the DRY principle but seems to me like the best option. Also consider trimming settings that are not useful. Do users really want to choose the suffix of their docker container names? Probably not, and including those unwanted options makes settings doc bloated and confusing.

**Comment by isaacliao** [comment]
As per discussion, one possible solution is to use [Ansible Roles](https://docs.ansible.com/ansible/playbooks_roles.html). Roles bundle playbooks, tasks, and vars together, letting users specify their own (default) settings and vars. 

So, for instance, a user could write a "Loom server in AWS" role and share it via [Ansible Galaxy](https://galaxy.ansible.com/). Then, another Loom user could specify that their server should use the "Loom server in AWS" role, and override only the specific settings that they need. All Loom would have to do is create a new instance and apply that role to it. (As for initially creating that instance, we might need a "Loom client in AWS" role or something.)

To see this in action, I believe this is how [Elasticluster](https://github.com/gc3-uzh-ch/elasticluster) handles the problem of supporting multiple cloud environments.

**Comment by nhammond** [comment]
You can now start in local mode with just "loom server start". fc22932e4c206d875e3ba7c6ce3c1369e3ce178d

gcloud settings were reduced to a minimal set f471ee46efaee0040ee88a1cd7ad76f187e2f39c: 

LOOM_MODE: gcloud
LOOM_GCE_PEM_FILE
LOOM_GCE_EMAIL
LOOM_GCE_PROJECT
LOOM_GOOGLE_STORAGE_BUCKET
