### ISSUE TITLE
gcloud_start_server playbook should validate server instance name; warning or error?

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#379]
If given an invalid instance name, should this be an error that halts execution, or should we strip out invalid characters, truncate, warn, and continue?

**Comment by nhammond** [comment]
Server name is used by both gcloud instance and docker container names. It can be invalid in either of these contexts, and possibly in other contexts for future deployment environments (e.g. AWS). If we can come up with a sensible set of rules that applies to all of these contexts but is not too restrictive, we can hard-code that in the "loom server start" command and either error out or truncate the name.

The safest option is to error and tell the user they are using an invalid server name. Truncating names brings a risk of the user specifying different names that are truncated to the same string. This could be confusing if the user is starting a new server but ansible acts on an existing VM with the same truncated name.

If we do find that one context is extremely restrictive (e.g. Google Cloud doesn't allow the letters A through M in instance names) we might have to handle errors raised in the playbooks. But I doubt that will be the case.

**Comment by isaacliao** [comment]
Okay, I'll close this since nothing needs to be done for now. The Ansible gce module will throw an error on invalid instance name in the gcloud_server_start playbook.
