### ISSUE TITLE
mysql_create_docker_container always evaluates as true

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#383]
Ansible now issues a warning when playbooks use "{{ }}" jinja notation in "when" statements.

However, certain expressions do not evaluate without the braces, producing a string value that evaluates as True, instead of a value of either True or False depending on settings.

The problem is with this var (in loomengine/client/playbooks/vars/common.yml):

    mysql_create_docker_container: lookup('env', 'LOOM_MYSQL_CREATE_DOCKER_CONTAINER') | bool

used in this expression (in loomengine/client/playbooks/tasks/start_server.yml):

    when: mysql_create_docker_container

**Comment by nhammond** [comment]
Fixed in ec4bcb68c02ca60c802709ff485210f403ac6feb

But this fix brings back the warning.

**Comment by isaacliao** [comment]
Yeah, I tried to fix those warnings too, and ended up reverting them because of the same issue.
