### ISSUE TITLE
loom server start --settings-file local.conf fails

### ISSUE THREAD

**Issue by zhangzhen** [StanfordBioinformatics/loom#397]
Can anyone solve this problem? The error message is listed below:

TASK [Configure Elasticsearch on Linux host] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/zhangz/.loom/playbooks/local_start_server.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1   

WARNING! An error occurred. Rolling back changes to settings.
ERROR! Playbook to start server failed. There may be active resources such as running docker containers or  VMs that were created by the playbook and not cleaned up.

Regards,
Zhen Zhang

**Comment by isaacliao** [comment]
Changed to ignore error if not root: 5324cfa39726efc3233808858f8a4e42d762c075
