### ISSUE TITLE
the task failed while running the example "word_scoring"

### ISSUE THREAD

**Issue by zhangzhen** [StanfordBioinformatics/loom#398]
The error is listed below:
500 Server Error: Internal Server Error ("{"message":"containerd: container not started"}").
Could one tell me why?

Regards,
Zhen Zhang

**Comment by nhammond** [comment]
Hi Zhen, this workflow uses some features that are still in development, and the workflow does not work. Please note this comment in the README file:

```
NOTE: This example does not work currently! The parallel feature is not yet available.
```

But I'm not sure that is the cause for the error you saw. Are you able to run the "hello_world" workflow, or does it raise the same error?

**Comment by zhangzhen** [comment]
Hi Nathan,
Sorry, I didn't notice this comment in the README file. I ran the "hello_world" workflow. No error was raised.

I wrote a pipeline on my own and used a glob pattern in it.
---
name: pgs_basic
inputs:
- type: string
  channel: sample
outputs:
- type: file
  channel: new_file
steps:
- name: prepare_raw_data
  command: cat {{ sample }}*R1*.fastq.gz > {{ sample }}.fastq.gz
  environment:
    docker_image: ubuntu
  resources:
    cores: '1'
    memory: '1'
  inputs:
  - type: string
    channel: sample
  outputs:
  - type: file
    channel: new_file
    source:
      filename: sample.fastq.gz

I got the following error while running it:
cat: '02X17043001*R1*.fastq.gz': No such file or directory

I specify the output filename like "filename: {{ sample }}.fastq.gz". This has a parsing error. How can I specify an output filename with a variable?

Regards,
Zhen

**Comment by sowmiu** [comment]
Hi Zhen, we appreciate your effort and patience with trying out LOOM as our documentation is bit lacking at this point. I have taken a crack at translating your workflow steps below and it ran successfully in my loom server. I am also sending the sequence of steps to import the template and files necessary to run the workflow

WORKFLOW FILE

name: test_zheng_workflow
inputs:  #Workflow inputs should be specified here
  - type: string
    channel: sampleid 

  - type: file
    channel: fastq_gz
outputs:       #Workflow outputs should be specified here
  - type: file
    channel: fastq
steps:
# Individual steps are defined here
  - name: prepare_raw_data 
    inputs: #inputs to individual steps are defined here, they can be ouputs of other steps or workflow inputs defined above
      - type: file
        channel: fastq_gz #refer to workflow input channel
      - type: string 
        channel: sampleid   #refer to workflow input channel         
    outputs: #outputs from individual steps are defined here
      - type: file
        channel: fastq
        source:
          filename: "{{sampleid}}.fastq" #Name of the output file refers to workflow input channel sampleid by enclosing in {{}}
     
    command: zcat {{fastq_gz}} > {{fastq}}  
    environment:
           docker_image: ubuntu
    resources:
           memory: "1" 
           cores: "1"
    


STEPS to IMPORT the template and files to run the workflow

Step 1: Import template
>>loom import template zheng.yaml 
>>Importing template from "file:///home/XXXXX/zheng.yaml".
>>Imported template "test_zheng_workflow@26fea4b8-ea71-43af-988b-b535dc1ee7dc".

Step 2: import your input fastq.gz file
>>loom import file SCGV1-01_reads1.fastq.gz
>>Calculating md5 on file "file:///home/XXXXX/SCGV1-01_reads1.fastq.gz"...
>>Importing file from file:///home/XXXXXX/SCGV1-01_reads1.fastq.gz...
>>   copying to destination gs://gbsc-gcp-project-scgs-dev-loom/loom-data/imported/2017-05-27T06.19.07Z_8f69dfa9_SCGV1-01_reads1.fastq.gz ...
>>   imported file SCGV1-01_reads1.fastq.gz@8f69dfa9-a146-43f3-9900-f0ce9a80219b

Step 3: Run your workflow, please note that I refer to the workflow and the input file using UUID assigned by LOOM.

>>loom run test_zheng_workflow@26fea4b8-ea71-43af-988b-b535dc1ee7dc sampleid="zheng" fastq_gz=SCGV1-01_reads1.fastq.gz@8f69dfa9-a146-43f3-9900-f0ce9a80219b
>>Created run test_zheng_workflow@d98a2c5a-3e5f-4ce6-b27b-9da4433f0431

Let us know if you need help with writing more multi-step workflow examples. 
Best
Sowmi


OUTPUT FROM LOOM SERVER UI
Runs 
Name	prepare_raw_data
Run ID	4dc3e0ac-dec2-4045-9ece-880b0bb3fe6c
Status	Finished
Created	May 26, 2017 11:27:40 PM
Template ID	6110bf50-d2c2-41ff-9b9e-7c7c3fe1f95a
Command	zcat {{fastq_gz}} > {{fastq}}
Interpreter	/bin/bash -euo pipefail
Inputs

Channel	Type	Data
fastq_gz	file	SCGV1-01_reads1.fastq.gz
sampleid	string	zheng
Outputs

Channel	Type	Data
fastq	file	zheng.fastq
Tasks

Task ID	Status	Created
a90ca80b-3f0a-4727-9a6e-606b0d8a3c41		2017-05-27 06:27:40.959919+00:00
Timepoints

Timestamp	Message	Is error	Detail
May 26, 2017 11:27:40 PM	Run prepare_raw_data@4dc3e0ac-dec2-4045-9ece-880b0bb3fe6c was created	false	
May 26, 2017 11:27:40 PM	Child Task a90ca80b-3f0a-4727-9a6e-606b0d8a3c41 was created	false	
May 26, 2017 11:40:04 PM	Child Task a90ca80b-3f0a-4727-9a6e-606b0d8a3c41 finished successfully	false	
May 26, 2017 11:40:04 PM	Run prepare_raw_data@4dc3e0ac-dec2-4045-9ece-880b0bb3fe6c finished successfully	false

**Comment by sowmiu** [comment]
Formatting completely ruins the YAML file. Let me try workflow definition file in JSON format

{
  "name": "test_zheng_workflow",
  "inputs": [
    {
      "type": "string",
      "channel": "sampleid"
    },
    {
      "type": "file",
      "channel": "fastq_gz"
    }
  ],
  "outputs": [
    {
      "type": "file",
      "channel": "fastq"
    }
  ],
  "steps": [
    {
      "name": "prepare_raw_data",
      "inputs": [
        {
          "type": "file",
          "channel": "fastq_gz"
        },
        {
          "type": "string",
          "channel": "sampleid"
        }
      ],
      "outputs": [
        {
          "type": "file",
          "channel": "fastq",
          "source": {
            "filename": "{{sampleid}}.fastq"
          }
        }
      ],
      "command": "zcat {{fastq_gz}} > {{fastq}}",
      "environment": {
        "docker_image": "ubuntu"
      },
      "resources": {
        "memory": "1",
        "cores": "1"
      }
    }
  ]
}

**Comment by zhangzhen** [comment]
Thank you very much!

I read through the code and appreciate the beauty of the architecture (master + client + portal + worker). You use the latest technology such as angular, elasticsearch, container, async (implemented with celery). Design patterns are also used to implement this engine. You answered my question very quickly. This gratifies me very greatly. I will develop a product based on this engine.

Regards,
Zhen Zhang

**Comment by nhammond** [comment]
This example has been renamed as "sentence_scoring", and it works now that the parallel workflow feature has been completed. It is also featured in the documentation here: http://loom.readthedocs.io/en/latest/templates.html#sentence-scoring

You can now use glob patterns for outputs like this:

```yaml
outputs:
  - channel: samples
    type: file
    mode: scatter
    source:
      glob: "*.fastq.gz"
```

Zhen, I'm marking this closed, but please let me know if you still have questions on this.
