### ISSUE TITLE
How can I delete or update a template after I've imported a template?

### ISSUE THREAD

**Issue by zhangzhen** [StanfordBioinformatics/loom#399]
I test a pipeline. Every time the pipeline is changed,  importing it creates a new one. I find it inconvenient. Is there a way to delete or update a template, except deleting it directly from the database?

Regards,
Zhen Zhang

**Comment by sowmiu** [comment]
Hi Zhen, thanks for you feedback. We understand that this causes an inconvenience at the early stage of learning to put together workflows. However, reproducibility is the key feature of LOOM and that is the reason we don't enable deleting or even changing an existing workflow. This would break the reproducibility. 

Any change to the workflow definition (even though the workflow name is the same) we assign new UUID and can be referred using <NAME>@<UUID>

Keep your feedbacks coming, it is very valuable for us.


Thanks and Best
Sowmi

**Comment by nhammond** [comment]
Although a template can't be changed per se, it is now possible to delete a template. A modified version can be imported to replace it. So the workflow for editing a template would be something like this:

loom template export myworkflow
loom template delete myworkflow
# make edits
loom template import myworkflow

(The old version can only be deleted if no runs or other templates refer to it.)

Even better, keep both the original and modified versions, and use tags to track version:
loom template import myworkflow --tag v1.0
# then later, after modifications
loom template import myworkflow --tag v1.1
