### ISSUE TITLE
If a pipeline fails, can re-runing the pipeline resume from where it fails?

### ISSUE THREAD

**Issue by zhangzhen** [StanfordBioinformatics/loom#403]
It is not uncommon that running a pipeline fails sometimes. So, if a pipeline fails, can re-runing the pipeline resume from where it fails?

Regards,
Zhen

**Comment by nhammond** [comment]
Zhen, I am marking this as an enhancement. It would be very useful.

**Comment by nhammond** [comment]
This is implemented since release 0.7.0. Unless you include LOOM_FORCE_RERUN=True in the settings or use the --force-rerun option with "loom run start", Loom will use a results from a previous or ongoing run if the tasks are identical.
