### ISSUE TITLE
Delay in flushing user process stderr/stdout to elasticsearch

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#407]
Expectation is that stderr/stdout will be up to date, with no more than ~a minute delay sending output from user processes to logs available in Kibana.

However, we are seeing that some logs do not show up in Kibana until the end or near-end of a long-running process.

**Comment by isaacliao** [comment]
Fixed by 40201fb77208e12ab9711f753d36a0bac9dc835b.
