### ISSUE TITLE
TaskAttempt status stays at "Waiting" even when running

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#408]
The StepRun and Task statuses are set to "Running", but the TaskAttempt status stays at "Waiting":
<img width="1337" alt="screenshot 2017-06-08 16 00 58" src="https://user-images.githubusercontent.com/1683569/26954325-304e34a4-4c64-11e7-9fbc-3aa68b4df960.png">

TaskAttempt:
<img width="1325" alt="screenshot 2017-06-08 16 01 12" src="https://user-images.githubusercontent.com/1683569/26954329-35d90ade-4c64-11e7-8e66-845dc0da5950.png">

Task:
<img width="1340" alt="screenshot 2017-06-08 16 06 32" src="https://user-images.githubusercontent.com/1683569/26954381-7c6566dc-4c64-11e7-871f-f654886d6e4f.png">

TaskAttempt container is running:
![screenshot 2017-06-08 16 02 46](https://user-images.githubusercontent.com/1683569/26954340-44629d54-4c64-11e7-91f6-8ca7ea5399fc.png)

**Comment by nhammond** [comment]
Closing issue because this behavior is no longer possible. No "Waiting" status on TaskAttempts.
