### ISSUE TITLE
Name gcloud instances to be able to distinguish servers

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#48]
Per request from Ranjan

Would it be possible to name the worker nodes to reflect the relationship with the loom server?
Worker-loom-srvr, worker-nathan-loom-server etc?

**Comment by isaacliao** [comment]
Definitely possible and useful. Which pieces of information should we include in the name? How about worker-$servername-$workflowname-$stepname?

**Comment by cmuthu** [comment]
Sure. This will help us to login to the worker straight easily to debug. Thanks for implementing.

**Comment by isaacliao** [comment]
Adding related request from Ranjan:

Is there a way to find the worker nodes from the loom page?

**Comment by isaacliao** [comment]
Implemented in: 194c9cb12063b752ae37edabffa95cc66dcba326

Adding request to find worker nodes from Loom browser as a separate issue.
