### ISSUE TITLE
Download speed from google storage is slower than expected

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#54]
When downloading inputs for a step run to a worker VM, a 3GB file (hg19.fa) takes 22 minutes, about 3 MB/s. Can we accelerate this? If not, need to evaluate requirements and consider alternative architectures.

**Comment by isaacliao** [comment]
For alternative architectures, I think we should look into Kubernetes. It uses scalable clusters of VM's to run containers. We could have a data container with often-used files like hg19 cached on the worker nodes.

**Comment by nhammond** [comment]
Tested download to VM with: 
zone: us-central-a
machine type: n1-standard-1 (1 vCPU, 3.75 GB memory)

Storage was under same project, with 
location: US
storage class: standard

3 trials. New instance each time. Last 2 were simultaneous. Download speeds were:
2.98 GB / 1m29.813s  = 34.0 MB/s
2.98 GB / 1m28.860s  = 34.3 MB/s
2.98 GB /1m29.033s  = 34.3 MB/s

1 trial with an instance in europe-west-1c
2.98 GB /1m35.604s  = 31.9 MB/s

1 trial with storage class Durable Reduced Availability
2.98 GB/1m48.523s = 28.1 MB/s

1 trial from a different project
2.98 GB/1m53.858s = 26.8 MB/s

This times are all ~10x the speed observed before creating this issue.

Failed to reproduce the problem.

**Comment by nhammond** [comment]
Expected performance as a function of disk type and size is outlined here.
https://cloud.google.com/compute/docs/disks/performance

We were using a 10 GB SSD persistent disk. The link above says that has a max sustained download speed of 10 GB * 0.12 MB/s (speed) / GB (disk size) = 4.8 MB/s, in line with what we were seeing.

The same link proposes the solution: Use a bigger disk, even if you don't need all the space. For example, with a VM with 1 core, top write speed is 78 MB/s. But there is a lower cap imposed unless you use a standard disk of >= 650 GB or an SSD disk of >= 163 GB.

With more cores, the max performance is higher and you need bigger disks to hit it. Best case is 240 MB/s, for which you need 4 cores and 500 GB of SSD.

Local disk (non-persistent) can do even better, with a peak of 1400 MB/s for SSD. Local disk performance is independent of disk size. You can use up to eight 375 GB local SSD partitions for 3 TB. You have to manage striping yourself if you want to hit peak performance, but encryption is built in.

**Comment by nhammond** [comment]
Closing as duplicate of https://github.com/StanfordBioinformatics/loom/issues/98
