### ISSUE TITLE
Non-string value found for env option

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#586]
When running Loom server start:

TASK [Start a container with celery workers to run asynchronous tasks] *********
fatal: [10.240.0.14]: FAILED! => {"changed": false, "msg": "Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid them being interpreted. Key: C_FORCE_ROOT"}

This appears to be caused either by a new version of either ansible (2.7.8 -> 2.8.0) or pyaml (3.13->5.1) installed with the Loom client. It is resolved by wrapping "true" in quotes for C_FORCE_ROOT in the playbook.

**Comment by nhammond** [comment]
Fixed in 9b5cbbcec4ab2e9adeaef8d119e728deb29e7bc0

**Comment by weyderfs** [comment]
> Fixed in [9b5cbbc](https://github.com/StanfordBioinformatics/loom/commit/9b5cbbcec4ab2e9adeaef8d119e728deb29e7bc0)

Here in my case not fix to me, the error continues:
`Ambiguous env options must be wrapped in quotes to avoid them being interpreted. Key: FTP_PORT"}`
