### ISSUE TITLE
Make worker deployment log files accessible from browser

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#59]
Currently writing several logs to /tmp
loom_ansible.log
loom_cloud_taskmanager.log
loom_task_manager2.log

These should be saved and accessible from the browser.

**Comment by isaacliao** [comment]
Files are now written to ~/.loom/log along with other log files. Still need to make them reachable from browser.

**Comment by nhammond** [comment]
Done. Logs are centralized in elasticsearch now.
