### ISSUE TITLE
Round trip objects in log files

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#76]
Workflows, Runs, and Files should be exportable/importable, and import should work for objects recorded in the logs.

**Comment by isaacliao** [comment]
What is the use case for exporting and importing objects to and from log files?

**Comment by nhammond** [comment]
2 separate but related items. 1. You should be able to export a workflow and let someone else run it. Export/import of runs and results might be a little more complicated since you need to transfer files as well, but this should be supported in some form. 2. If we are logging these objects, they should be usable in the same way that exported objects can be used. Currently there may be glitches that can prevent you from re-importing a workflow or other object that you downloaded or that was written to a log file. One problem is that having pre-defined id's causes an error when you're creating a new object, and there may be other issues as well since we haven't been testing for this.

**Comment by isaacliao** [comment]
Sounds good. I did run into problems serializing a TaskRun object to a JSON, so this is worth looking into.

**Comment by nhammond** [comment]
This is now doable by having the worker call loomengine_utils.export_manager.ExportManager.export_run() using link_files=True.

**Comment by nhammond** [comment]
No action planned. It is now possible to export and re-import complete runs.
