### ISSUE TITLE
GCP deployment should adhere to Django best practices checklist

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#77]
Need to conform to best practices for django.
https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

**Comment by isaacliao** [comment]
Automated GCP deployment is functional, but not Django best practices. Changed the title to reflect this.

**Comment by nhammond** [comment]
Enforced CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE in e2dc6cc32b65b602be92c77f58b9484cc59b26be. HTTPS required to enable login in 87c90e0793cd80aa51eacdabe39d55304abf152b.
