### ISSUE TITLE
Automate release to pypi

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#81]
Each commit on master should trigger a pypi release

**Comment by isaacliao** [comment]
- Need to make sure VERSION is incremented before pushing to master
- How to authenticate with PyPI?
- Learn how to write a git hook

**Comment by isaacliao** [comment]
If possible, could also watch VERSION file for changes, and release to PyPI when it changes.

**Comment by nhammond** [comment]
Closing this ticket--not sure automatic release to PyPi with every commit is very practical idea. Opening instead a ticket for including release to pypi in our release process. #312
