### ISSUE TITLE
Improve hashing of import files

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#9]
- Currently need to hash every import file twice: once for pipeline specification JSON, and again when xppf_upload.py copies to fileserver
- Can't get hash from server because the hash is the identifier
- xppf_upload.py could read -hashes.json, but would have to trust that files haven't changed since hashes were generated
- Fileserver could verify hashes of files asynchronously (does it do this already?), and mark files as invalid
- md5sum takes ~6 minutes for 80 GB file
- Consider using hash trees for parallelization (https://pythonhosted.org/pyskein/)

**Comment by isaacliao** [comment]
Idea: -hashes.json can store the datetime that each hash was generated. Then, when xppf_compile runs, it can compare to each file's modification time and only hash if it's more recent.

Also, xppf_upload can take a parameter to read from -hashes.json and do something similar.

Since we have similar functionality between xppf_compile and xppf_upload, consider moving all of this to a centralized hashing class.

**Comment by nhammond** [comment]
Fixed by 2088e1fc4e98d9e4f9bfc6
